"""initDatabase

Revision ID: c58aa233139c
Revises: 
Create Date: 2025-02-23 10:28:41.165559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c58aa233139c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('key_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('orders',
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('client_ip', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PAYED', 'FAILED', name='orderstatusid'), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=64), nullable=True),
    sa.Column('role', sa.Enum('USER', 'ADMIN', name='userroleid'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('auth_tokens',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('token', sa.String(length=128), nullable=False),
    sa.Column('expiration_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('alias', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=8192), nullable=True),
    sa.Column('visible', sa.Boolean(), nullable=True),
    sa.Column('system_requirements', sa.String(length=1024), nullable=True),
    sa.Column('current_price', sa.Integer(), nullable=True),
    sa.Column('old_price', sa.Integer(), nullable=True),
    sa.Column('key_category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['key_category_id'], ['key_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game_genre',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], ),
    sa.PrimaryKeyConstraint('game_id', 'genre_id')
    )
    op.create_table('order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', postgresql.UUID(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('preview_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=255), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_name', sa.String(length=128), nullable=True),
    sa.Column('text', sa.String(length=1024), nullable=True),
    sa.Column('rating', sa.SmallInteger(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=64), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('order_item_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['key_categories.id'], ),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('value')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('keys')
    op.drop_table('reviews')
    op.drop_table('preview_images')
    op.drop_table('order_items')
    op.drop_table('game_genre')
    op.drop_table('games')
    op.drop_table('auth_tokens')
    op.drop_table('users')
    op.drop_table('orders')
    op.drop_table('key_categories')
    op.drop_table('genres')
    # ### end Alembic commands ###
